### ISSUE TITLE
[Question]: 'MInferenceConfig' has no attribute 'get_available_kv_types' and 'get_available_attn_types'

### ISSUE THREAD

**Issue by rainstorm12** [microsoft/MInference#102]
### Describe the bug

I have install the package ‘minference-0.1.5.post1+cu118torch2.3-cp310-cp310-linux_x86_64.whl’ 

when I run the test of scbench,  there is a bug in args.py
  File "/myfile/MInference-main/scbench/run_scbench.py", line 268, in <module>
    args = parse_args()
  File "/myfile/MInference-main/scbench/args.py", line 92, in parse_args
    choices=MInferenceConfig.get_available_kv_types(),
AttributeError: type object 'MInferenceConfig' has no attribute 'get_available_kv_types'.

In the class MInferenceConfig, I can't find the function of 'get_available_kv_types' and 'get_available_attn_types'

**Comment by rainstorm12** [comment]
Another issue is that upon reviewing the code of the **Minference** library, it appears that the current Minference only supports the selection of **attention_type**, but does not support the selection of **kv_type**, as shown in the following code:
```python
class MInference:
    def __init__(
        self,
        attn_type: str = "minference",
        model_name: str = None,
        config_path: str = None,
        starting_layer: int = -1,
        kv_cache_cpu: bool = False,
        use_snapkv: bool = False,
        is_search: bool = False,
        attn_kwargs: dict = {},
        **kwargs,
    ):
        super(MInference, self).__init__()
        self.config = MInferenceConfig(
            attn_type=attn_type,
            model_name=model_name,
            config_path=config_path,
            starting_layer=starting_layer,
            kv_cache_cpu=kv_cache_cpu,
            use_snapkv=use_snapkv,
            is_search=is_search,
            attn_kwargs=attn_kwargs,
            **kwargs,
        )

    def __call__(self, model):
        return self.patch_model(model)

    def patch_model(self, model):
        if self.config.attn_type != "vllm":
            model.config.starting_layer = self.config.starting_layer
            model.config.config_path = self.config.config_path

        if self.config.attn_type == "minference":
            model.config.is_search = self.config.is_search
            model = minference_patch(model, self.config)

        elif self.config.attn_type == "minference_with_dense":
            model.config.dense = True
            model = minference_patch(model, self.config)

        elif self.config.attn_type == "dilated1":
            model.config.dilated1 = True
            model = minference_patch(model, self.config)

        elif self.config.attn_type == "static":
            model.config.static_pattern = True
            model = minference_patch(model, self.config)

        elif self.config.attn_type == "dilated2":
            model.config.dilated2 = True
            model = minference_patch(model, self.config)
...
```
Additionally, the available **attention_type** options do not seem to match the descriptions provided in the scripts
 file (**run_all_task.sh**) of **scbench**，as shown in the following code:
```python
ATTN_KV_TYPES=(
    "vllm;dense" # FullAttention
    "vllm_minference;dense" "vllm_a_shape;dense" "vllm_tri_shape;dense" # 1) KV Cache Generation Stage
    "dense;streamingllm" "dense;snapkv" "dense;pyramidkv" "dense;kivi" # 2) KV Cache Compression Stage
    "vllm_blend;dense" # 3) KV Cache Retrieval Stage
    "dense;quest" "dense;retr_attn" # 4) KV Cache Loading Stage
)
```
So is it because the current  MInference library has not been updated yet?

**Comment by iofu728** [comment]
Hi @rainstorm12,  

Apologies, as we are still validating the completeness of SCBench, the code has not yet been updated in the new pip release.  

In the meantime, please install it from the source using the following command. We will release the updated version ASAP.  

```bash
git clone https://github.com/microsoft/MInference
pip install -e .
```

Additionally, for MInference `kv_type`, you can pass it in using this https://github.com/microsoft/MInference/blob/main/minference/models_patch.py#L21.  

Let me know if you encounter any issues!

**Comment by rainstorm12** [comment]
thank you, I solved my problem
