### ISSUE TITLE
[Question]: RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cuda:1)

### ISSUE THREAD

**Issue by LiweiPE** [microsoft/MInference#25]
### Describe the issue

The bug is produced when running in multi gpus, since I only can test benchmark_e2e.py with --context_window 512000. Then, I used dual card for Qwen2-7B for context 1M and this error is produced. How to fix?
![image](https://github.com/microsoft/MInference/assets/48242387/cfd06c6e-dded-4c25-b897-ac33b01ecda4)

**Comment by iofu728** [comment]
Fixed in #30, please try to use `pip install minference -U`.
