### ISSUE TITLE
[Question]: Very low quality outputs for long sequences

### ISSUE THREAD

**Issue by cckao** [microsoft/MInference#29]
### Describe the issue

Model: `Qwen2-7B-Instruct`

When the length of input sequence exceeded 131072, which is the value of `sliding_window` in the `config.json`, I saw following message and got very bad and short output.

`Token indices sequence length is longer than the specified maximum sequence length for this model (150021 > 131072). Running this sequence through the model will result in indexing errors`

Does anyone know how to fix this issue? Thank you.

**Comment by iofu728** [comment]
Hi @cckao, thank you for your interest in MInference.

In fact, MInference does not alter the inherent capabilities of any Long-context LLMs. For instance, Qwen2-7B natively supports only up to 128K context windows. Using inputs larger than 128K will result in performance degradation. Additionally, our experiments indicate that the performance of the Qwen2-7B model starts to significantly decline at around 83K, as shown in Figure 9(g).
