### ISSUE TITLE
[Question]: "Building wheel for flash_attn (setup.py) " for a long time without any notification 

### ISSUE THREAD

**Issue by qiling1345** [microsoft/MInference#37]
### Describe the issue

Requirement already satisfied: mpmath>=0.19 in ./python/3.10.12/lib/python3.10/site-packages (from sympy->torch->minference) (1.2.1)
Building wheels for collected packages: minference, flash_attn
  Building wheel for minference (setup.py) ... done
  Created wheel for minference: filename=minference-0.1.4.post2-cp310-cp310-linux_x86_64.whl size=3547476 sha256=93f5a7f879dafae55626633576005655e19b00c388a48ff8ad1bdf32993ed52f
  Stored in directory: /root/.cache/pip/wheels/42/57/2b/cc98ec52e123b55cca8d6830dc696017d312a553c67bb49024
  Building wheel for flash_attn (setup.py) ... \

**Comment by iofu728** [comment]
Please upgrade MInference to version 0.1.4.post3, which does not depend on flash_attn. You can do this by running the following command:

```bash
pip install minference==0.1.4.post3
```
