### ISSUE TITLE
[Question]: I got this error "No CUDA GPUs are available", how can I run with CPU ?

### ISSUE THREAD

**Issue by qiling1345** [microsoft/MInference#38]
### Describe the issue

No CUDA GPUs are available

**Comment by qiling1345** [comment]
support only GPU？Is NPU supported?

**Comment by iofu728** [comment]
Hi @qiling1345, thanks for your support.

MInference currently only supports GPU. This is because it relies on optimal GPU kernels to perform dynamic sparse calculations, and long-context scenarios have high computational resource requirements. It does not support CPU or NPU environments.
