### ISSUE TITLE
[Question]: run with local models

### ISSUE THREAD

**Issue by qiling1345** [microsoft/MInference#41]
### Is your feature request related to a problem? Please describe.

I want to run my models locally, rather than online.

**Comment by iofu728** [comment]
Hi @qiling1345, thanks for your support.

Currently, MInference supports loading local models. You can use it as follows. Please note that the `model_name` parameter should correspond to the appropriate Hugging Face model name instead of the local path.

```python
local_path = "xxx"
model = AutoModelForCausalLM.from_pretrained(local_path)

# Need to use the actual model name in the HF repo
model_name = "Qwen/Qwen2-7B-Instruct"
minference_patch = MInference("minference", model_name)
model = minference_patch(model)
```

**Comment by qiling1345** [comment]
thank you！

**Comment by luo647** [comment]
> 你好@qiling1345， 感谢您的支持。
> 
> 目前MInference支持加载本地模型，你可以按照如下方式使用，注意参数`model_name`要对应到合适的Hugging Face模型名，而不是本地路径。
> 
> ```python
> local_path = "xxx"
> model = AutoModelForCausalLM.from_pretrained(local_path)
> 
> # Need to use the actual model name in the HF repo
> model_name = "Qwen/Qwen2-7B-Instruct"
> minference_patch = MInference("minference", model_name)
> model = minference_patch(model)
> ```

Will you support [CodeQwen1.5-7b-base](https://huggingface.co/Qwen/CodeQwen1.5-7B) or [DeepSeekCoder6.7b-base]

**Comment by iofu728** [comment]
> > 你好@qiling1345， 感谢您的支持。
> > 目前MInference支持加载本地模型，你可以按照如下方式使用，注意参数`model_name`要对应到合适的Hugging Face模型名，而不是本地路径。
> > ```python
> > local_path = "xxx"
> > model = AutoModelForCausalLM.from_pretrained(local_path)
> > 
> > # Need to use the actual model name in the HF repo
> > model_name = "Qwen/Qwen2-7B-Instruct"
> > minference_patch = MInference("minference", model_name)
> > model = minference_patch(model)
> > ```
> 
> Will you support [CodeQwen1.5-7b-base](https://huggingface.co/Qwen/CodeQwen1.5-7B) or [DeepSeekCoder6.7b-base]

Hi @luo647, thanks for your suggestion. We'll try to support DeepSeek v2 in the next version.
