### ISSUE TITLE
[Question]: Hi，it seems that Qwen2-7B-Instruct is not support in my case

### ISSUE THREAD

**Issue by lwj2001** [microsoft/MInference#48]
### Describe the bug

i have encouter a error that:
`AssertionError: The model model/qwen/Qwen2-7B-Instruct you specified is not supported. You are welcome to add it and open a PR :)`
maybe the model not have been downloaded from Hugging Face, but rather from ModelScope?

### Steps to reproduce

my script is that:
```
from vllm import LLM, SamplingParams
from minference import MInference
model_name = "model/qwen/Qwen2-7B-Instruct"
sampling_params = SamplingParams(temperature=0.7, top_p=0.8, repetition_penalty=1.05)
prompt = "Tell me something about large language models."
llm = LLM(model_name, max_num_seqs=1, enforce_eager=True, max_model_len=32768)

minference_patch = MInference("vllm", model_name)
llm = minference_patch(llm)

outputs = llm.generate(prompt, sampling_params)
```

### Additional Information

vllm_version :0.5.0, and minference is build from source

**Comment by iofu728** [comment]
Hi @lwj2001, thanks for your feedback.

Since you are using a local path, please use the model name from HF when initializing MInference. Please refer to #41.
