### ISSUE TITLE
[Question]:  FlashAttention only supports Ampere GPUs or newer

### ISSUE THREAD

**Issue by qiling1345** [microsoft/MInference#51]
### Describe the issue

env:
minference==0.1.4.post2
flash-attn==2.6.0.post1
transformers== 4.42.4

GPU：Tesla V100S
NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4

**Comment by qiling1345** [comment]
How can I set FlashAttention to false?

**Comment by iofu728** [comment]
Hi @qiling1345, you need to upgrade MInference to a version greater than 0.1.4.post3.

**Comment by qiling1345** [comment]
I upgrade MInference to 0.1.4.post4，but this problem is not solved。

  File "/opt/huawei/python/3.10.12/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 51, in _flash_attn_forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.fwd(
RuntimeError: FlashAttention only supports Ampere GPUs or newer.
