### ISSUE TITLE
[Question]: AssertionError: The model /workspace/model/llm/Qwen/Qwen2-7B-Instruct you specified is not supported. 

### ISSUE THREAD

**Issue by LIUKAI0815** [microsoft/MInference#60]
### Describe the bug

AssertionError: The model /workspace/model/llm/Qwen/Qwen2-7B-Instruct you specified is not supported. You are welcome to add it and open a PR

**Comment by iofu728** [comment]
Hi @LIUKAI0815,

Thanks for your feedback.

If you're using a local model, you need to provide the model name from Hugging Face. You can follow the guidelines from this [link](https://github.com/microsoft/MInference?tab=readme-ov-file#how-to-use-minference).

```python
local_path = "xxx"
model = AutoModelForCausalLM.from_pretrained(local_path)

# Need to use the actual model name in the HF repo
model_name = "Qwen/Qwen2-7B-Instruct"
minference_patch = MInference("minference", model_name)
model = minference_patch(model)
```

**Comment by LIUKAI0815** [comment]
thank you
