### ISSUE TITLE
[Bug]: Normalization of QK product to estimate top-k tokens and slashes

### ISSUE THREAD

**Issue by PiotrNawrot** [microsoft/MInference#69]
### Describe the bug

[Here](https://github.com/microsoft/MInference/blob/main/minference/modules/minference_forward.py#L376), which I presume is the main function called during inference, you don't normalize the QK product by `math.sqrt(self.head_dim)`.

Is it intended, or is it a typo?

**Comment by iofu728** [comment]
Hi @PiotrNawrot, It was great meeting you at ICML!

Thank you for pointing that out—I forgot to fix the issue. In our experience, resolving it should improve the results. I'll make sure to address it today.

**Comment by PiotrNawrot** [comment]
[Hm, I had some issue with Github I guess because I think it didn't register my answer]

It was absolutely blast meeting you at ICML @iofu728; thanks once again for this amazing work and keep this up; no rush - I raised this issue in a good will, in case I managed to spot this typo : )

PS. I DMed you on Twitter with one question, let me know if you prefer some other medium

**Comment by iofu728** [comment]
Hi @PiotrNawrot,

The issue has been fixed in #70. Please try upgrading to the latest version of MInference.

I'll also debug and check the issue with LLaMA-3.1-8B in RULER.
